server:
  port: 10105
spring:
  application:
    name: gisq-bi
  #  profiles:
  #    active: dev #  项目运行使用哪个配置文件 dev  1041 1104  11110  11129  5129  province shigl
  datasource:
    validationQuery: SELECT 1
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/gisqbi?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8&allowMultiQueries=true
    username: root
    password: MTMtLRgADX4=
  #    url: jdbc:mysql://127.0.0.1:3306/gisqbi?characterEncoding=utf-8
  #    username: root
  #    password: root
  redis:
    #database: 0
    #非集群使用
    port: 6379
    host: localhost
    #密码
    #password:
    timeout: 3000 #连接超时时间（毫秒）
    pool:
      # 连接池中的最大空闲连接
      max-idle:  3000
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 6000
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
  http:
    multipart:
      # 上传图片时的临时文件路径
      location: F:\BI\uploadfile\data\upload_tmp
      maxFileSize: 100Mb
      maxRequestSize: 1000Mb



mybatis:
  type-aliases-package: com.gisquest.datavisual.dao.*
  mapper-locations:
    - classpath*:mapper/*/*.xml

#security:
#  basic:
#    enabled: false

gisq:
  form:
    enabled: true  # 修改为true
    service-url: http://localhost:18088/api  # 表单后台接口地址
  config:
    encrypt: true
  csrf:
    enabled: true
    host:  59.202.53.27:10104
  cloud:
    sso:
      enable: 1
      can-parse-token-local: 0  #启用本地token解析，不推荐，可能导致token伪造
      zuul-host: localhost:19088,localhost:10008
  bizlog:
    enabled: true
  dataVisual:
    # 系统管理员账号
    adminName: admin
    # 新添加用户的初始密码
    # newUserPassWord: {usercode}@22W
    # 新添加用户的默认角色
    # newUserRole: visitor
    # 是否开放BI平台对外接口免认证请求/thirdparty/gisqbi
  enabledGisqbiServicePublic:
    dataLocalCategory: true
    dataLocal: true

  screenshot:
    # 截屏等待时间，毫秒，如果有载入较慢的组件，可以适当延长192.168.11.123  b0650fa
    waitTime: 5000
    visual:
      # 因为有些云平台，内网和外网地址不同，所以添加host替换配置，不需要替换，设置为空
      # screenshot.vusial.host替换refer中的看板地址（eg: 127.0.0.1:10104）
      host: 127.0.0.1:10104
  globalParams:
    # 注意如果需要设置外部登录页面，请使用全地址，如https://192.168.1.1/sso-login
    # 注意如果需要带上跳转地址，请将该参数放置在最后，如 https://192.168.1.1/sso-login?redirect=
    loginPage:
  aggregator:
    h2:
      url: jdbc:h2:~/H2Data/datav;AUTO_SERVER=TRUE;LOG=0;UNDO_LOG=0
  cache:
    redis:
      hostName: localhost
      port: 6379
  rest:
    connection:
      timeout: 15000 # 连接超时时间 单位：ms
    read:
      timeout: 15000 # 信息读取超时时间 单位：ms

# JWT
jwt:
  header: X-Gisq-Token
  deviceId: X-Gisq-DeviceId
  secret: gisq39561c9fe068
  #token有效期1月
  expiration: 2592000
  tokenHead: "Bearer "
  serverAutoLoginHead: X-Gisq-Login
  autoLoginUserId: admin
  autoLoginPassword: admin

#打印Mybatis执行的SQL
logging:
  level:
    #    root: ERROR
    com.gisquest.datavisual.dao: ERROR
    com.gisquest.datavisual.screenshot: ERROR
  pattern:
    level: ERROR

# 图片视频文件上传到服务器的存储路径
imageFile:
  baseURL: /images
  realPath: F:\BI\uploadfile
customFile:
  baseURL: /custom
  realPath: ${imageFile.realPath}
eureka:
  client:
    service-url:
      defaultZone: http://192.168.11.73:9081/eureka/
    enabled: false  # 与电子政务5.0集成认证体系时  需要设置为 true，若BI独立使用时,必须设置为false

# 第三方系统接口调用地址（大数据和AI系统）
thirdparty:
  timeout: 90
  ai:
    service-url: http://192.168.9.88:8080
    queryModelServiceAndDiagram: /modelService/queryModelServiceAndVersion
  dataBrain:
    service-url: http://192.168.9.86:1111/databrain-spatial
    remoteProject: /remote/project
    remoteModels: /remote/models
    remoteModel: /remote/model
